#!/bin/bash
#
# download-agent-data.sh - Sync agent-generated data from server to local tmp folder
#
# This script efficiently downloads all data generated by the live-SWE-agent on the server
# to the local tmp/agent_work folder using rsync, avoiding re-downloads of unchanged files.
#
# Features:
# - Incremental sync (only transfers changed files)
# - Efficient rsync-based transfers
# - Excludes temporary files (*.tmp, *.lock)
# - Preserves file permissions and timestamps
# - Dry-run mode to preview changes
# - Force mode for full resync
#
# Usage:
#   ./download-agent-data.sh              # Incremental sync (recommended)
#   ./download-agent-data.sh --dry-run    # Preview what would be synced
#   ./download-agent-data.sh --force      # Full sync (transfers all files)
#   ./download-agent-data.sh --help       # Show help
#
# What gets synced:
# - creative_output/ (agent's creative work)
# - knowledge/ (learned knowledge and insights)
# - logs/ (session logs and history)
# - projects/ (generated code and projects)
# - state/ (agent state and configuration)
# - temp/ (temporary files, excluding *.tmp)
# - tools/ (custom tools created by agent)
# - SYSTEM_PROMPT.md and other config files
#

set -e

SERVER="debian"
REMOTE_DIR="~/ai_home"
LOCAL_DIR="./tmp/agent_work"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}✓${NC} $1"; }
log_warn() { echo -e "${YELLOW}⚠${NC} $1"; }
log_error() { echo -e "${RED}✗${NC} $1"; }
log_step() { echo -e "\n${BLUE}==>${NC} $1"; }
log_file() { echo -e "   ${BLUE}📄${NC} $1"; }

# Parse arguments
DRY_RUN=false
FORCE=false

for arg in "$@"; do
    case $arg in
        --dry-run)
            DRY_RUN=true
            ;;
        --force)
            FORCE=true
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --dry-run    Show what would be synced without actually doing it"
            echo "  --force      Force full sync (ignore timestamps)"
            echo "  --help       Show this help"
            echo ""
            echo "This script syncs agent data from server ($SERVER:$REMOTE_DIR)"
            echo "to local folder ($LOCAL_DIR) using rsync for efficiency."
            exit 0
            ;;
    esac
done

echo "========================================"
echo "   Agent Data Sync Script"
echo "========================================"
echo ""

# Check SSH connectivity
log_step "Checking server connectivity..."
if ! ssh -o ConnectTimeout=5 "$SERVER" "echo 'OK'" > /dev/null 2>&1; then
    log_error "Cannot connect to server '$SERVER'"
    echo "Make sure the server is running and SSH is configured."
    exit 1
fi
log_info "Connected to $SERVER"

# Create local directory if it doesn't exist
log_step "Ensuring local directory exists..."
mkdir -p "$LOCAL_DIR"
log_info "Local directory ready: $LOCAL_DIR"

# Build rsync options
RSYNC_OPTS="-avz --delete"
RSYNC_OPTS="$RSYNC_OPTS --exclude='.git/'"
RSYNC_OPTS="$RSYNC_OPTS --exclude='*.tmp'"
RSYNC_OPTS="$RSYNC_OPTS --exclude='*.lock'"
RSYNC_OPTS="$RSYNC_OPTS --exclude='.last_sync'"

if [ "$DRY_RUN" = true ]; then
    RSYNC_OPTS="$RSYNC_OPTS --dry-run"
    echo ""
    log_warn "DRY RUN MODE - No files will be actually transferred"
fi

if [ "$FORCE" = true ]; then
    RSYNC_OPTS="$RSYNC_OPTS --ignore-times"
    log_warn "FORCE MODE - Ignoring timestamps, full sync"
fi

# Show what we're doing
echo ""
echo "Sync Configuration:"
echo "  From: $SERVER:$REMOTE_DIR/"
echo "  To:   $LOCAL_DIR/"
echo "  Mode: $([ "$DRY_RUN" = true ] && echo 'DRY RUN' || echo 'LIVE')"
echo ""

# Perform the sync
log_step "Starting rsync sync..."

# Use --itemize-changes to see exactly what rsync does with each file
# Format: YXcstpoguax where:
#   Y = update type: < sent, > received, c local change, h hard link, . no update, * message
#   X = file type: f file, d directory, L symlink, D device, S special
#   c = checksum differs, s = size differs, t = time differs, p = perms differ
RSYNC_OPTS="$RSYNC_OPTS --itemize-changes"

# Capture rsync output to parse transferred files
RSYNC_OUTPUT=$(rsync $RSYNC_OPTS -e ssh "$SERVER:$REMOTE_DIR/" "$LOCAL_DIR/" 2>&1)
RSYNC_EXIT=$?

# Parse output to find actually transferred files (not just checked)
# Files that were transferred have patterns like:
#   >f+++++++++ = new file received
#   >f.st...... = file updated (size/time changed)
#   >f..t...... = file updated (time changed)
#   >f.s....... = file updated (size changed)
#   *deleting   = file deleted
# Note: >f........... (all dots) means file was checked but not changed
TRANSFERRED_FILES=$(echo "$RSYNC_OUTPUT" | grep -E "^>f|^\*deleting" | grep -v "^>f\.\.\.\.\.\.\.\.\.\.\." || true)
if [ -n "$TRANSFERRED_FILES" ]; then
    TRANSFERRED_COUNT=$(echo "$TRANSFERRED_FILES" | wc -l)
else
    TRANSFERRED_COUNT=0
fi

# Show what happened
if [ "$DRY_RUN" = true ]; then
    echo "Files that would be synced:"
    echo "----------------------------------------"
    if [ "$TRANSFERRED_COUNT" -gt 0 ] && [ -n "$TRANSFERRED_FILES" ]; then
        echo "$TRANSFERRED_FILES" | head -20 | while read -r line; do
            # Extract just the filename from the itemize output
            filename=$(echo "$line" | sed 's/^[^ ]* //')
            if echo "$line" | grep -q "^\*deleting"; then
                echo -e "   ${RED}🗑${NC}  $filename (would be deleted)"
            elif echo "$line" | grep -q "^>f+++"; then
                echo -e "   ${GREEN}📥${NC} $filename (new file)"
            else
                echo -e "   ${YELLOW}📝${NC} $filename (updated)"
            fi
        done
        if [ "$TRANSFERRED_COUNT" -gt 20 ]; then
            echo "   ... and $(($TRANSFERRED_COUNT - 20)) more files"
        fi
        echo ""
        log_info "$TRANSFERRED_COUNT file(s) would be transferred"
    else
        log_info "All files are up to date - nothing to transfer"
    fi
else
    echo "Transferred files:"
    echo "----------------------------------------"
    if [ "$TRANSFERRED_COUNT" -gt 0 ] && [ -n "$TRANSFERRED_FILES" ]; then
        echo "$TRANSFERRED_FILES" | head -20 | while read -r line; do
            # Extract just the filename from the itemize output
            filename=$(echo "$line" | sed 's/^[^ ]* //')
            if echo "$line" | grep -q "^\*deleting"; then
                echo -e "   ${RED}🗑${NC}  $filename (deleted)"
            elif echo "$line" | grep -q "^>f+++"; then
                echo -e "   ${GREEN}📥${NC} $filename (new)"
            else
                echo -e "   ${YELLOW}📝${NC} $filename (updated)"
            fi
        done
        if [ "$TRANSFERRED_COUNT" -gt 20 ]; then
            echo "   ... and $(($TRANSFERRED_COUNT - 20)) more files"
        fi
        echo ""
        log_info "$TRANSFERRED_COUNT file(s) transferred"
    else
        log_info "All files are identical - nothing was transferred"
    fi
fi

# Check rsync exit status
if [ $RSYNC_EXIT -eq 0 ] || [ $RSYNC_EXIT -eq 24 ]; then  # 24 = vanished files (not an error)
    if [ "$DRY_RUN" = true ]; then
        log_info "Dry run completed successfully"
    else
        log_info "Sync completed successfully"
    fi
elif [ $RSYNC_EXIT -eq 23 ]; then  # Partial transfer due to vanished files
    log_warn "Sync completed with some vanished files (this is usually normal)"
else
    log_error "Rsync failed with exit code $RSYNC_EXIT"
    echo "Rsync output:"
    echo "$RSYNC_OUTPUT"
    exit $RSYNC_EXIT
fi

# Show summary if not dry run
if [ "$DRY_RUN" = false ]; then
    echo ""
    log_step "Sync Summary"

    # Count files and directories
    FILE_COUNT=$(find "$LOCAL_DIR" -type f | wc -l)
    DIR_COUNT=$(find "$LOCAL_DIR" -type d | wc -l)
    TOTAL_SIZE=$(du -sh "$LOCAL_DIR" 2>/dev/null | cut -f1)

    echo "  Directories: $DIR_COUNT"
    echo "  Files:       $FILE_COUNT"
    echo "  Total size:  $TOTAL_SIZE"

    # Show recent files (last 24 hours)
    echo ""
    echo "Recently modified files (last 24h):"
    echo "----------------------------------------"
    find "$LOCAL_DIR" -type f -mtime -1 -print | head -10 | while read -r file; do
        log_file "$(basename "$file")"
    done

    if [ $(find "$LOCAL_DIR" -type f -mtime -1 | wc -l) -gt 10 ]; then
        echo "   ... and $(($(find "$LOCAL_DIR" -type f -mtime -1 | wc -l) - 10)) more"
    fi
fi

echo ""
log_info "Sync operation complete!"

# Show usage hint
echo ""
echo "Tip: Run './sync-agent-data.sh --dry-run' to preview changes before syncing."