#!/bin/bash

DEFAULT_METHOD="openrouter"
MODEL_PROVIDER="openrouter"
MODEL_NAME="arcee-ai/trinity-large-preview:free"
FALLBACK_MODELS="openrouter/z-ai/glm-4.5-air:free"
OPENROUTER_API_BASE="https://openrouter.ai/api/v1"
SESSION_TIMEOUT_SECONDS=1800
SESSIONS_PER_LIFE_STAGE=8
MAX_TOOL_CALLS=8
TOOL_COMMAND_TIMEOUT_SECONDS=45
MAX_TOOL_OUTPUT_CHARS=12000
TEMPERATURE=0.7
MODEL_RETRY_COUNT=2
MODEL_RETRY_DELAY_SECONDS=5
